apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # en lowercase sinon ca plante regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  name: root-apps
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: argocd-apps
    repoURL: https://github.com/aitkarrafarid/gitops-m2ili.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true