apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: default
    name: in-cluster
  project: projet-m2ili
  source:
    path: apps/nginx
    repoURL: https://github.com/aitkarrafarid/gitops-m2ili.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true